//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ATATool.rc
//
#define IDCHANGEPWD                     3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ATATOOL_DIALOG              102
#define IDD_PROPPAGE_MEDIUM_WIFI        106
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CONFIG               131
#define IDD_PROPPAGE_MEDIUM_GPS         132
#define IDD_PROPPAGE_MEDIUM_FM          133
#define IDD_PROPPAGE_MEDIUM_AUDIO       134
#define IDI_ICON_LISTCTRL               134
#define IDD_PROPPAGE_MEDIUM_MATV        135
#define IDD_PROPPAGE_MEDIUM_VIBRATOR    136
#define IDD_PROPPAGE_MEDIUM_BT          137
#define IDD_PROPPAGE_MEDIUM_HWVER       138
#define IDD_PROPPAGE_MEDIUM_EARTHPHONE  139
#define IDD_PROPPAGE_MEDIUM_BTS         139
#define IDD_PROPPAGE_MEDIUM_CAMERA      140
#define IDD_PROPPAGE_MEDIUM_KPAD        141
#define IDD_PROPPAGE_PM_CAL             142
#define IDD_PROPPAGE_MEDIUM_LED         143
#define IDD_PROPPAGE_MEDIUM_SENSOR      144
#define IDD_DIALOG_INPUT_PASSWD         146
#define IDD_DIALOG_CHANGE_PWD           149
#define IDD_PROPPAGE_MEDIUM_MICBIAS     150
#define IDC_STATIC_MAIN_RECT            1000
#define IDC_BUTTON_START_ALL            1006
#define IDC_BUTTON_STOP_ALL             1007
#define IDC_LIST_DUT1                   1008
#define IDC_STATIC_LINE                 1009
#define IDC_LIST_DUT2                   1010
#define IDC_LIST_DUT3                   1011
#define IDC_CHECK_SW                    1011
#define IDC_LIST_DUT4                   1012
#define IDC_CHECK_BARCODE               1012
#define IDC_CHECK_TCARD                 1013
#define IDC_BUTTON_CONFIG               1013
#define IDC_CHECK_SIM                   1014
#define IDC_STATIC_LINE2                1014
#define IDC_CHECK_GPS                   1015
#define IDC_CHECK_VIBRATOR              1016
#define IDC_CHECK_CHARGER               1017
#define IDSAVE                          1019
#define IDC_CHECK_WIFI                  1020
#define IDC_CHECK_BT                    1021
#define IDC_CHECK_FM                    1022
#define IDC_CHECK_MATV                  1023
#define IDC_CHECK_SPEAKER               1024
#define IDC_CHECK_RECEIVER              1025
#define IDC_CHECK_EARTHPHONE            1026
#define IDC_CHECK_EXT_BUCK              1027
#define IDC_CHECK_BAROMETER             1028
#define IDC_CHECK_HUMIDITY              1029
#define IDC_CHECK_BTS                   1030
#define IDC_EDIT_FM_FREQ                1031
#define IDC_EDIT_FM_CHIP                1032
#define IDC_EDIT_FM_CQI                 1033
#define IDC_EDIT_WIFI_MAC               1033
#define IDC_EDIT_MATV_CHIP              1034
#define IDC_EDIT_WIFI_RSSI              1034
#define IDC_EDIT_VIBRATOR_CURR_MAX      1034
#define IDC_STATIC_COUNTRY              1035
#define IDC_EDIT_AUDIO_EARTHPHONE       1035
#define IDC_CHECK_ACT1                  1043
#define IDC_CHECK_ACT2                  1047
#define IDC_CHECK_ACT3                  1051
#define IDC_CHECK_ACT4                  1055
#define IDC_COMBO_COM1                  1058
#define IDC_COMBO_FC1                   1059
#define IDC_EDIT_AUDIO_SPEAKER          1059
#define IDC_EDIT_SPEAKER_MIN_FREQ_L     1059
#define IDC_COMBO_BAUD1                 1060
#define IDC_EDIT_AUDIO_RECEIVER         1060
#define IDC_EDIT_RECEIVER_MIN_FREQ_L    1060
#define IDC_COMBO_COM2                  1061
#define IDC_EDIT_MATV_FREQ              1061
#define IDC_EDIT_SPEAKER_MAX_FREQ_L     1061
#define IDC_COMBO_FC2                   1062
#define IDC_COMBO_MATV_COUNTRY          1062
#define IDC_EDIT_SPEAKER_MIN_AMP_L      1062
#define IDC_COMBO_BAUD2                 1063
#define IDC_EDIT_VIBRATOR_CURR_MIN      1063
#define IDC_EDIT_SPEAKER_MAX_AMP_L      1063
#define IDC_COMBO_COM3                  1064
#define IDC_EDIT_GPS_PHASE_RATIO        1064
#define IDC_EDIT_RECEIVER_MAX_FREQ_L    1064
#define IDC_COMBO_FC3                   1065
#define IDC_EDIT_GPS_TXCO_OFFSET        1065
#define IDC_EDIT_RECEIVER_MIN_AMP_L     1065
#define IDC_COMBO_BAUD3                 1066
#define IDC_EDIT_GPS_TXCO_DRIFT         1066
#define IDC_EDIT_RECEIVER_MAX_AMP_L     1066
#define IDC_COMBO_COM4                  1067
#define IDC_EDIT_GPS_CNR_MEAN           1067
#define IDC_COMBO_FC4                   1068
#define IDC_EDIT_GPS_CNR_SIGMA          1068
#define IDC_EDIT_SPEAKER_MIN_FREQ_R     1068
#define IDC_COMBO_BAUD4                 1069
#define IDC_EDIT_GPS_UPDATE_HZ          1069
#define IDC_EDIT_SPEAKER_MAX_FREQ_R     1069
#define IDC_EDIT_GPS_BIT_SYNC           1070
#define IDC_CHECK_LCM                   1070
#define IDC_EDIT_SPEAKER_MIN_AMP_R      1070
#define IDC_EDIT_GPS_ACQUISION          1071
#define IDC_EDIT_SPEAKER_MAX_AMP_R      1071
#define IDC_EDIT_GPS_SVID               1072
#define IDC_EDIT_BT_ADDR                1072
#define IDC_EDIT_RECEIVER_MIN_FREQ_R    1072
#define IDC_EDIT_RECEIVER_MAX_FREQ_R    1073
#define IDC_EDIT_VIBRATOR_CURRENT_DIFF_MIN 1074
#define IDC_EDIT_RECEIVER_MIN_AMP_R     1074
#define IDC_EDIT_PSU_GPIB_ADDR          1075
#define IDC_EDIT_RECEIVER_MAX_AMP_R     1075
#define IDC_EDIT_PSU_GPIB_ADDR2         1076
#define IDC_EDIT_PSU_GPIB_ADDR3         1077
#define IDC_COMBO_SIM_NUM               1078
#define IDC_EDIT_PSU_GPIB_ADDR4         1078
#define IDC_CHECK_TP                    1079
#define IDC_CHECK_CAMERA                1080
#define IDC_EDIT_WAIT_SEC               1081
#define IDC_CHECK_HW                    1082
#define IDC_EDIT_VOL_MIN                1083
#define IDC_EDIT_HEADSET_MIN_FREQ_L     1083
#define IDC_CHECK_CAMERA_SUB            1083
#define IDC_EDIT_VOL_MAX                1084
#define IDC_EDIT_HEADSET_MAX_FREQ_L     1084
#define IDC_EDIT_TEST_ITEM_TIMEOUT      1084
#define IDC_EDIT_HEADSET_MIN_AMP_L      1085
#define IDC_CHECK_CAMERA2               1085
#define IDC_CHECK_RTC                   1086
#define IDC_EDIT_HEADSET_MAX_AMP_L      1086
#define IDC_EDIT_GPIO                   1087
#define IDC_EDIT_HEADSET_MIN_FREQ_R     1087
#define IDC_EDIT_SW_SUBSTR              1088
#define IDC_EDIT_HEADSET_MAX_FREQ_R     1088
#define IDC_COMBO_STATUS                1089
#define IDC_EDIT_AP_SW                  1089
#define IDC_EDIT_HEADSET_MIN_AMP_R      1089
#define IDC_EDIT_HEADSET_MAX_AMP_R      1090
#define IDC_CHECK_ER_STATE              1092
#define IDC_EDIT_SENSOR_ID              1093
#define IDC_EDIT_FAIL_RATE              1094
#define IDC_CHECK_KPAD                  1095
#define IDC_EDIT_COL0                   1097
#define IDC_COMBO_SPEC_TYPE             1097
#define IDC_EDIT_ROW0                   1098
#define IDC_CHECK_ADC                   1098
#define IDC_EDIT_COL1                   1099
#define IDC_EDIT_ADC_V1                 1099
#define IDC_EDIT_ROW1                   1100
#define IDC_EDIT_ADC_V2                 1100
#define IDC_CHECK_SLPMODE               1100
#define IDC_EDIT_COL2                   1101
#define IDC_EDIT_ADC_MAX_DIFF           1101
#define IDC_CHECK_OFFMODE               1101
#define IDC_EDIT_ROW2                   1102
#define IDC_EDIT_SLPMOD_CURRENT         1102
#define IDC_CHECK_OTG                   1102
#define IDC_EDIT_COL3                   1103
#define IDC_EDIT_RETRY_TIMES            1103
#define IDC_EDIT_OFFMOD_CURRENT         1103
#define IDC_EDIT_ROW3                   1104
#define IDC_EDIT_LOOP_TIMES             1104
#define IDC_BUTTON_1                    1104
#define IDC_EDIT_COL4                   1105
#define IDC_BUTTON_3                    1105
#define IDC_EDIT_BARCODE                1105
#define IDC_CHECK_HDMI                  1105
#define IDC_EDIT_ROW4                   1106
#define IDC_BUTTON_4                    1106
#define IDC_CHECK_RSS                   1106
#define IDC_EDIT_COL5                   1107
#define IDC_BUTTON_2                    1107
#define IDC_EDIT_RSSI                   1107
#define IDC_CHECK_GSENSOR               1107
#define IDC_EDIT_ROW5                   1108
#define IDC_CHECK_LED                   1108
#define IDC_EDIT_RSSI_LTE               1108
#define IDC_EDIT_COL6                   1109
#define IDC_CHECK_MSENSOR               1109
#define IDC_EDIT_ROW6                   1110
#define IDC_EDIT_PSU1                   1110
#define IDC_EDIT_KERNEL_PORT1           1110
#define IDC_EDIT_COL7                   1111
#define IDC_EDIT_PSU2                   1111
#define IDC_EDIT1_CHRGR_MAX             1111
#define IDC_EDIT_KERNEL_PORT2           1111
#define IDC_EDIT_ROW7                   1112
#define IDC_EDIT_PSU3                   1112
#define IDC_EDIT_CHRGR_MIN              1112
#define IDC_EDIT_KERNEL_PORT3           1112
#define IDC_EDIT_PSU4                   1113
#define IDC_EDIT_KERNEL_PORT4           1113
#define IDC_CHECK_AUTO_POLL             1114
#define IDC_CHECK_EMMC                  1115
#define IDC_EDIT_PRELOADER_PORT1        1116
#define IDC_EDIT_PRELOADER_PORT2        1117
#define IDC_EDIT_PRELOADER_PORT3        1118
#define IDC_EDIT_PRELOADER_PORT4        1119
#define IDC_CHECK_COMPOSITE             1120
#define IDC_CHECK_CMMB                  1121
#define IDC_EDIT_PM_COM1                1122
#define IDC_EDIT_VOL_11                 1123
#define IDC_CHECK_ALSPS                 1123
#define IDC_EDIT_ADC_11                 1124
#define IDC_CHECK_GYROSCOPE             1124
#define IDC_EDIT_PM_COM2                1125
#define IDC_EDIT_VOL_12                 1125
#define IDC_EDIT_PM_COM3                1126
#define IDC_EDIT_ADC_12                 1126
#define IDC_EDIT_PM_COM4                1127
#define IDC_BUTTON_CONVERT_1            1127
#define IDC_EDIT_SLOPE_1                1128
#define IDC_EDIT_LED_STATE              1128
#define IDC_CHECK_STOP_IF_FAIL          1128
#define IDC_EDIT_OFFSET_1               1129
#define IDC_CHECK_MICBIAS               1129
#define IDC_EDIT_VOL_21                 1130
#define IDC_EDIT_GSENSOR_X_MAX          1130
#define IDC_CHECK_MHL                   1130
#define IDC_EDIT_ADC_21                 1131
#define IDC_EDIT_BARCODE_FLAG_INDEX     1131
#define IDC_CHECK_USBTYPEC              1131
#define IDC_EDIT_VOL_22                 1132
#define IDC_EDIT_GSENSOR_X_MIN          1132
#define IDC_EDIT_PASS_FLAG              1132
#define IDC_CHECK_FINGERPRINT           1132
#define IDC_EDIT_ADC_22                 1133
#define IDC_EDIT_GSENSOR_Y_MAX          1133
#define IDC_EDIT_FAIL_FLAG              1133
#define IDC_CHECK_BARCODE_FLAG          1133
#define IDC_BUTTON_CONVERT_2            1134
#define IDC_EDIT_GSENSOR_Y_MIN          1134
#define IDC_EDIT_PASSWD_INPUT           1134
#define IDC_EDIT_SLOPE_2                1135
#define IDC_EDIT_GSENSOR_Z_MAX          1135
#define IDC_GPS_Cali                    1135
#define IDC_EDIT_OFFSET_2               1136
#define IDC_EDIT_GSENSOR_Z_MIN          1136
#define IDC_EDIT_MSENSOR_X_MAX          1137
#define IDC_EDIT_MSENSOR_X_MIN          1138
#define IDC_EDIT_MSENSOR_Y_MAX          1139
#define IDC_EDIT_MSENSOR_Y_MIN          1140
#define IDC_EDIT_OLD_PWD                1140
#define IDC_EDIT_MSENSOR_Z_MAX          1141
#define IDC_EDIT_NEW_PWD1               1141
#define IDC_CHECK_KEY_EXTER_CONN        1141
#define IDC_EDIT_MSENSOR_Z_MIN          1142
#define IDC_EDIT_NEW_PWD2               1142
#define IDC_EDIT_BIAS0_MIN              1142
#define IDC_EDIT_ALS_MAX                1143
#define IDC_EDIT_BIAS0_MAX              1143
#define IDC_CHECK_ELEC_MAG_SWITCH       1143
#define IDC_EDIT_ALS_MIN                1144
#define IDC_EDIT_BIAS1_MIN              1144
#define IDC_EDIT_PS_MAX                 1145
#define IDC_EDIT_BIAS1_MAX              1145
#define IDC_EDIT_PS_MIN                 1146
#define IDC_EDIT_OTG_MIN                1146
#define IDC_CHECK_GS_X                  1147
#define IDC_EDIT_OTG_MAX                1147
#define IDC_CHECK_GS_Y                  1148
#define IDC_CHECK_VIBRATOR_ON_BOARD     1148
#define IDC_EDIT_GYROSCOPE_X_MAX        1149
#define IDC_EDIT_GYROSCOPE_X_MIN        1150
#define IDC_EDIT_GYROSCOPE_Y_MAX        1151
#define IDC_EDIT_GYROSCOPE_Y_MIN        1152
#define IDC_EDIT_GYROSCOPE_Z_MAX        1153
#define IDC_EDIT_GYROSCOPE_Z_MIN        1154
#define IDC_CHECK_GS_Z                  1155
#define IDC_CHECK_GSENSOR_DIFF          1156
#define IDC_STATIC_SPEC                 1157
#define IDC_CHECK_SELECT_ALL1           1159
#define IDC_CHECK_SELECT_ALL2           1160
#define IDC_CHECK_SELECT_ALL3           1161
#define IDC_CHECK_WIFI_MAC              1161
#define IDC_CHECK_SELECT_ALL4           1162
#define IDC_CHECK_CHECK_SUM             1163
#define IDC_EDIT_CHECKSUM_MAIN_CAMERA   1164
#define IDC_EDIT_VOL_31                 1165
#define IDC_EDIT_CHECKSUM_SUBCAMERA     1165
#define IDC_CHECK_ALS                   1165
#define IDC_EDIT_ADC_31                 1166
#define IDC_CHECK_PS                    1166
#define IDC_EDIT_BT_HOSTADDR            1166
#define IDC_EDIT_CHECKSUM_MAIN_CAMERA2  1166
#define IDC_EDIT_VOL_32                 1167
#define IDC_CHECK_BT_ADDR               1167
#define IDC_EDIT_ADC_32                 1168
#define IDC_EDIT_BTS_TEMP_MIN           1168
#define IDC_EDIT_SOC_TEMP_MIN           1168
#define IDC_BUTTON_CONVERT_3            1169
#define IDC_EDIT_BTS_TEMP_MAX           1169
#define IDC_EDIT_SOC_TEMP_MAX           1169
#define IDC_EDIT_SLOPE_3                1170
#define IDC_EDIT_MDPA_TEMP_MIN          1170
#define IDC_EDIT_OFFSET_3               1171
#define IDC_EDIT_MDPA_TEMP_MAX          1171
#define IDC_EDIT_VOL_41                 1172
#define IDC_EDIT_ADC_41                 1173
#define IDC_EDIT_VOL_42                 1174
#define IDC_EDIT_ADC_42                 1175
#define IDC_BUTTON_CONVERT_4            1176
#define IDC_EDIT_SLOPE_4                1177
#define IDC_EDIT_OFFSET_4               1178

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1170
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
